### ISSUE TITLE
Feature: --ignore argument feature

### ISSUE THREAD

**Issue by fluentinstroll** [Joy3van/linked-out#1]
I'd like to add a --ignore option to allow users to make txt files of urls they would like to ignore when they use the app.

Further information in [this link](https://github.com/Seneca-CDOT/topics-in-open-source-2020/wiki/lab-4#requirements) but basically the app should accept a file name and ignore the links (only with http:// or https://) written within, force close if the file is invalid in the ways specified in the link.

Would love to add this!

**Comment by Joy3van** [comment]
Hi Raymond, by all means!

**Comment by fluentinstroll** [comment]
@Joy3van Hello again! sorry for taking so long, I was kinda busy this week haha - check out my [branch](https://github.com/fluentinstroll/linked-out/tree/issue-1) to see my code and let me know if there's anything you'd like changed! thanks.

The usage is ```linkedout -f <file> -i <ignore file>```

**Comment by Joy3van** [comment]
@fluentinstroll Sorry for the late reply. 
Looking great! However, I noticed that calling `linkedout` only doesn't show the help menu anymore so I made some changes. Also, now the `-i` option can be inserted ahead of `-f ` or even without specifying `-f`.
You can check my fix here:
```bash
$ git add upstream https://github.com/Joy3van/linked-out.git
$ git fetch upstream
$ git checkout -b issue-1-fix upstream/issue-1-fix
```
